const products = [
    {
        _id: '1',
        name: 'Nike Air Force 1',
        price: 100,
        image: 'https://placehold.co/400',
        rating: 1,
        numReviews: 10,
        countInStock: 100,
        description: 'This is a test',
        brand: 'Nike',
        category: 'Footwear'
    },
    {
        _id: '2',
        name: 'Adidas Ultraboost',
        price: 120,
        image: 'https://placehold.co/400',
        rating: 4,
        numReviews: 20,
        countInStock: 50,
        description: 'Comfortable running shoes',
        brand: 'Adidas',
        category: 'Footwear'
    },
    {
        _id: '3',
        name: 'Sony WH-1000XM4',
        price: 300,
        image: 'https://placehold.co/400',
        rating: 5,
        numReviews: 150,
        countInStock: 30,
        description: 'Noise-canceling over-ear headphones',
        brand: 'Sony',
        category: 'Electronics'
    },
    {
        _id: '4',
        name: 'Apple iPhone 13',
        price: 999,
        image: 'https://placehold.co/400',
        rating: 4.5,
        numReviews: 200,
        countInStock: 20,
        description: 'Latest model smartphone from Apple',
        brand: 'Apple',
        category: 'Electronics'
    },
    {
        _id: '5',
        name: 'Samsung Galaxy S21',
        price: 899,
        image: 'https://placehold.co/400',
        rating: 4,
        numReviews: 180,
        countInStock: 25,
        description: 'High-end Android smartphone',
        brand: 'Samsung',
        category: 'Electronics'
    },
    {
        _id: '6',
        name: 'Dell XPS 13',
        price: 1200,
        image: 'https://placehold.co/400',
        rating: 4.7,
        numReviews: 100,
        countInStock: 15,
        description: 'Compact and powerful laptop',
        brand: 'Dell',
        category: 'Computers'
    },
    {
        _id: '7',
        name: 'Canon EOS R5',
        price: 3500,
        image: 'https://placehold.co/400',
        rating: 4.8,
        numReviews: 50,
        countInStock: 10,
        description: 'Professional mirrorless camera',
        brand: 'Canon',
        category: 'Cameras'
    },
    {
        _id: '8',
        name: 'Bose QuietComfort 35 II',
        price: 299,
        image: 'https://placehold.co/400',
        rating: 4.5,
        numReviews: 120,
        countInStock: 40,
        description: 'Wireless noise-canceling headphones',
        brand: 'Bose',
        category: 'Electronics'
    },
    {
        _id: '9',
        name: 'Fitbit Charge 4',
        price: 150,
        image: 'https://placehold.co/400',
        rating: 4,
        numReviews: 300,
        countInStock: 70,
        description: 'Fitness and activity tracker',
        brand: 'Fitbit',
        category: 'Wearables'
    },
    {
        _id: '10',
        name: 'GoPro HERO9 Black',
        price: 400,
        image: 'https://placehold.co/400',
        rating: 4.6,
        numReviews: 80,
        countInStock: 60,
        description: 'Action camera with 5K video',
        brand: 'GoPro',
        category: 'Cameras'
    },
    {
        _id: '11',
        name: 'Apple AirPods Pro',
        price: 250,
        image: 'https://placehold.co/400',
        rating: 4.7,
        numReviews: 100,
    }
];
module.exports = products